name: flutter_web_navigation
version: 1.0.0+1
publish_to: none
description: A new Flutter project.

environment:
  sdk: '>=2.18.0 <3.0.0'

dependencies:
  after_layout: ^1.2.0
  csc_picker: ^0.2.6
  cupertino_icons: ^1.0.2
  dio: ^4.0.6
  dynamic_height_grid_view: ^0.0.3
  flutter:
    sdk: flutter
  flutter_dropzone: ^3.0.5
  go_router: ^5.0.5
  image_cropper: ^3.0.0
  image_picker: ^0.8.6
  intl: ^0.17.0
  keyboard_dismisser: ^3.0.0
  mime: ^1.0.2
  modal_bottom_sheet: ^2.1.2
  permission_handler: ^10.1.0
  pretty_dio_logger: ^1.1.1
  responsive_framework: ^0.2.0
  url_strategy: ^0.2.0
  wechat_assets_picker: ^8.1.2
  wechat_camera_picker: ^3.6.1

dev_dependencies:
  flutter_lints: ^2.0.1
  flutter_test:
    sdk: flutter
  pubspec_dependency_sorter: ^0.0.1

flutter:
  uses-material-design: true
